# Generated by Django 4.1.13 on 2024-02-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='degwidget',
            name='additional_export',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='degwidget',
            name='alias',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='degwidget',
            name='deg',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='degwidget',
            name='fields_list',
            field=models.JSONField(default=None),
        ),
        migrations.AddField(
            model_name='degwidget',
            name='img',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='degwidget',
            name='order',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='degwidget',
            name='russian_name',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='degwidget',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='degwidget',
            name='table_name',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='degwidget',
            name='type',
            field=models.TextField(choices=[('EXPORT', 'Export'), ('BOARD', 'Board')], default='EXPORT'),
        ),
    ]
