# Generated by Django 5.0.2 on 2024-02-20 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0002_degwidget_additional_export_degwidget_alias_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DegWidget',
        ),
    ]
